CREATE TABLE questao (
	id serial PRIMARY KEY,
	pergunta VARCHAR(2000) NOT NULL,
	nivel VARCHAR(20) NOT NULL,
	area_conhecimento VARCHAR(50) NOT NULL,
	resposta_correta VARCHAR(10) NOT NULL
);



INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('A ____________ é uma das áreas da(o) ___________ responsável pelo estudo do movimento dos corpos, sem levar em conta suas causas. A ___________ de um corpo é uma das mais importantes grandezas da Cinemática e representa a razão entre a(o) _________ por um corpo e a(o) ____________ decorrido(a) desse movimento.\na) Dinâmica; Física; aceleração; variação de velocidade; intervalo de tempo\nb) Cinemática; Física; velocidade; deslocamento sofrido; intervalo de tempo\nc) Hidrostática; Física; pressão; força aplicada; energia\nd) Relatividade; Mecânica; aceleração; dilatação sofrida; mudança de comprimento\ne) Cinemática; Física; velocidade; trajetória; intervalo de tempo', 'FACIL', 'FÍSICA', 'B');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('A Termodinâmica é uma das mais importantes áreas da Física. Uma de suas leis, conhecida como 1ª lei da Termodinâmica, estabelece que:\na) o zero absoluto é inalcançável.\nb) a transferência de calor para um sistema termodinâmico fechado aumenta o módulo de sua entropia.\nc) o estado termodinâmico de qualquer sistema depende de variáveis como pressão, volume e temperatura.\nd) a luz que passa por um meio transparente pode sofrer desvios angulares laterais em decorrência da mudança de velocidade que ela sofre ao ser refratada.\ne) a energia total em um sistema fechado é mantida constante, podendo sofrer transformações sem alterar seu módulo inicial\n', 'FACIL', 'FÍSICA', 'E');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('Charles Coulomb foi o responsável pela determinação da lei matemática que nos permite calcular o módulo da força exercida mutuamente pelos corpos eletricamente carregados. Tal lei afirma que:\na) o módulo da força magnética, seja ela atrativa, seja ela repulsiva, é dado pela razão do módulo das cargas elétricas dividida pelo quadrado da distância entre essas cargas.\nb) a força de atração exercida entre cargas elétricas é maior para o corpo carregado com maior carga elétrica.\nc) o módulo da força elétrica, seja ela atrativa, seja ela repulsiva, é dado pelo produto do módulo das cargas elétricas dividido pelo quadrado da distância entre essas cargas.\nd) a força elétrica exercida mutuamente por cargas elétricas depende exclusivamente do módulo dessas cargas.\ne) a força elétrica exercida entre cargas elétricas depende da massa das cargas e da distância entre elas.\n', 'FACIL', 'FÍSICA', 'C');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('James Clerk Maxwell foi um dos mais importantes nomes da Física. Assinale a alternativa que não representa uma de suas contribuições:\na) Cálculo da velocidade da luz\nb) Confirmação da natureza ondulatória da luz\nc) Unificação entre magnetismo e eletricidade\nd) Descoberta dos raios X\ne) Determinação da propagação transversal das ondas eletromagnéticas\n', 'MEDIA', 'FÍSICA', 'D');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('Um veículo trafega em uma rodovia com velocidade média de 80 km/h. Sabendo que a viagem teve uma duração de 1 hora e 30 minutos (1,5 h), qual foi a distância percorrida pelo veículo?\na) 80 km\nb) 10 kmc) 120 kmd) 160 kme) 100 km', 'MEDIA', 'FÍSICA', 'C');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('Um veículo automotivo acelera a 2,0 m/s², durante 5,0 s, a partir de uma velocidade inicial de 2,0 m/s. A distância percorrida por esse veículo, durante esse intervalo de tempo, é igual a:\na) 30 m\nb) 20 m\nc) 35 m\nd) 25 m\ne) 40 m\n', 'MEDIA', 'FÍSICA', 'C');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('Um motorista dirigia a 30 m/s quando avista um buraco na pista e pisa no freio. Os freios produziram uma desaceleração de 2,0 m/s², até que o carro para completamente. O espaço percorrido pelo veículo até o final da frenagem é de:\na) 150 m\nb) 125 m\nc) 225 m\nd) 275 m\ne) 450 m\n', 'MEDIA', 'FÍSICA', 'C');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('Uma locomotiva afasta-se de um observador enquanto sua velocidade aumenta a cada segundo. O movimento descrito por essa locomotiva pode ser classificado como:\na) progressivo e retardado.\nb) regressivo e retardado.\nc) progressivo e retilíneo.\nd) regressivo e acelerado.\ne) progressivo e acelerado.\n', 'DIFICIL', 'FÍSICA', 'E');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('(UNIFICADO-RJ) Dentro de um elevador, um objeto de peso 100 N está apoiado sobre uma superfície. O elevador está descendo e freando com aceleração vertical e para cima de 0,1 m/s2. Considere a aceleração da gravidade como 10 m/s2. Durante o tempo de frenagem, a força que sustenta o objeto vale, em newtons:\na) 101\nb) 99\nc) 110\nd) 90\ne) 100\n', 'DIFICIL', 'FÍSICA', 'A');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('(UEA) Um objeto, que se desloca horizontalmente com velocidade v0, é submetido à ação de uma força constante de intensidade F que o acelera, levando-o a atingir a velocidade v em um intervalo de tempo t. Nessas condições, é correto afirmar que a massa do objeto vale:\na) (v – v0) ÷ F.t\nb) F.t ÷ (v – v0)\nc) F.(v – v0) ÷ t\nd) (F – v) ÷ v0.t\ne) v.t ÷ (F – v0)\n', 'DIFICIL', 'FÍSICA', 'B');


INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('A Biologia Celular, ou citologia, é a parte da Biologia responsável por estudar o funcionamento das células e suas estruturas. Analise as alternativas a seguir e marque aquela que indica corretamente o nome do pesquisador que denominou essas estruturas funcionais dos seres vivos de células.\na) Theodor Schwann.\nb) Mathias Schleiden.\nc) Rudolf Virchow.\nd) Robert Hooke.\ne) Walther Flemming.\n', 'FACIL', 'BIOLOGIA', 'D');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('A Teoria Celular pode ser resumida, atualmente, em três pontos principais. Analise e marque a alternativa que não apresenta uma afirmação relacionada com essa teoria.\na) Todos os seres vivos são formadas por uma ou mais células.\nb) Todas as células são formadas por membrana, citoplasma e núcleo.\nc) As células são as unidades funcionais dos organismos vivos.\nd) Uma célula só pode originar-se de outra existente.\n', 'FACIL', 'BIOLOGIA', 'B');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('Costuma-se dizer que as células são formadas por membrana, citoplasma e núcleo. Entretanto, não são todas as células que apresentam um núcleo definido e delimitado por membrana nuclear. Baseando-se nisso, o mais correto seria afirmar que todas as células possuem membrana, citoplasma e material genético.\nAs células que apresentam núcleo definido são chamadas de\na) autotróficas.\nb) heterotróficas.\nc) eucarióticas.\nd) procarióticas.\ne) termófilas.\n', 'FACIL', 'BIOLOGIA', 'C');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('A membrana plasmática é encontrada em todas as células e apresenta como função principal controlar a entrada e a saída de substâncias no interior dessa estrutura. Essa membrana é formada por uma bicamada fosfolipídica onde estão inseridas algumas proteínas. O modelo que descreve a estrutura da membrana plasmática recebe o nome de:\na) modelo de permeabilidade seletiva.\nb) modelo de organização membranar.\nc) modelo fosfolipídico.\nd) modelo do mosaico fluido.\ne) modelo celular.\n', 'MEDIA', 'BIOLOGIA', 'D');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('(Enem) A estratégia de obtenção de plantas transgênicas pela inserção de transgenes em cloroplastos, em substituição à metodologia clássica de inserção do transgene no núcleo da célula hospedeira, resultou no aumento quantitativo da produção de proteínas recombinantes com diversas finalidades biotecnológicas. O mesmo tipo de estratégia poderia ser utilizada para produzir proteínas recombinantes em células de organismos eucarióticos não fotossintetizantes, como as leveduras, que são usadas para produção comercial de várias proteínas recombinantes e que podem ser cultivadas em grandes fermentadores.\nConsiderando a estratégia metodológica descrita, qual organela celular poderia ser utilizada para inserção de transgenes em leveduras?\na) Lisossomo.\nb) Mitocôndria.\nc) Peroxissomo.\nd) Complexo golgiense.\ne) Retículo endoplasmático.\n', 'MEDIA', 'BIOLOGIA', 'B');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('(Fatec- SP) Os espermatozoides são células muito ativas, com enorme capacidade de movimentação. Durante sua formação (espermatogênese) ocorrem várias fases diferentes, cuja sequência é:a) espermatogônia, espermátide, espermatócito I, espermatócito II e espermatozoide.\nb) espermátide, espermatócito I, espermatócito II, espermatogônia e espermatozoide.\nc) espermatócito I, espermatócito II, espermátide, espermatogônia e espermatozoide.\nd) espermatócito I, espermatócito II, espermatogônia, espermátide e espermatozoide.\ne) espermatogônia, espermatócito I, espermatócito II, espermátide e espermatozoide.\n', 'MEDIA', 'BIOLOGIA', 'E');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('A formação dos espermatozoides ocorre no interior do (a) ______________ e esse processo recebe o nome de ______________ .\nMarque a alternativa que completa adequadamente os espaços acima.\na) epidídimo e espermiogênese.\nb) testículo e espermatogênese.\nc) túbulos deferentes e espermiogênese.\ne) próstata e espermatogênese.\n', 'MEDIA', 'BIOLOGIA', 'B');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('Nos espermatozoides, é possível encontrar uma região rica em enzimas que facilitam a penetração do gameta no ovócito. Entre as alternativas a seguir, marque aquela que indica, respectivamente, o nome dessa estrutura e o nome da organela que a origina.\na) Flagelo e lisossomo.\nb) Acrossomo e complexo golgiense.\nc) Microssomo e retículo endoplasmático liso.\nd) Zona pelúcida e complexo golgiense.\ne) Bainha mitocondrial e lisossomo.\n', 'DIFICIL', 'BIOLOGIA', 'B');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('No início do processo de formação dos espermatozoides, as espermatogônias, encontradas nos tubos seminíferos, sofrem mitoses e iniciam um período de crescimento e duplicação dos cromossomos. Nesse momento, as células transformam-se em:\na) espermatócitos I.\nb) espermatócitos II.\nc) espermátides.\nd) espermatócitos.\n', 'DIFICIL', 'BIOLOGIA', 'A');
INSERT INTO questao (pergunta, nivel, area_conhecimento, resposta_correta) VALUES ('(Cesgranrio-RJ) Sabe-se que a sequência da espermatogênese é a seguinte:\nEspermatogônias → espermatócitos I → espermatócitos II → espermátides → espermatozoides.\nPergunta-se: quantos espermatozoides serão produzidos, respectivamente, a partir de 100 espermátides e 100 espermatócitos I?\na) 400 e 400.\nb) 100 e 800.\nc) 100 e 400.\nd) 400 e 100.\ne) 200 e 400.\n', 'DIFICIL', 'BIOLOGIA', 'C');

